### ISSUE TITLE
DockerHub "gulp build" error

### ISSUE THREAD

**Issue by reflog** [ottemo/store-ng#9]
Hi guys.
Still trying to get this thing to run:

docker pull ottemo/store-ng
FATA[0002] Tag latest not found in repository ottemo/store-ng 

Vagrant:
Vagrantfile mentions bootstrap.sh instead of bootstrap-linux.sh

Is the current code supposed to be in runnable state?

**Comment by vastbinderj** [comment]
@maazghani can you work with @reflog to get this running.  At this point, everything should be working except for images on products.  

I have expectations that even product images should be displaying correctly for the example store code very soon.

**Comment by vastbinderj** [comment]
@reflog are you trying to deploy it with docker to view the website or to check out our code?

We use docker to deploy to our dev, test and staging servers.  We use vagrant to create developer instances.  You can also just clone the repo, install gulp, node and bower, then use 'gulp serve' to bring up node webserver with a watch task.  

@maazghani I think it is very clear we have not defined well the 3 different was to run our client apps.  @reflog, I apologize for the lack of clarity in our current documentation.

**Comment by maazghani** [comment]
@reflog Currently the "gulp build" step is failing on DockerHub but not locally on Docker, so there is no latest tag yet since the automated build did not succeed. If you git-clone the repository and then run a "sudo docker build ." from within the directory, it will build the docker image locally and then you can run the container.

Alternatively you can clone the repository and build it using gulp from our instructions in the [INSTALL.MD](https://github.com/ottemo/store-ng/blob/develop/INSTALL.md). 

For further assistance, please visit us on our IRC channel #ottemo on [freenode](https://webchat.freenode.net).
